// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4OfUS33wIOMVJWb-Ki6loQdlkSpCqhAQ',
    appId: '1:484422805952:android:9a78e3348bd9fed40dc025',
    messagingSenderId: '484422805952',
    projectId: 'rugodymur-9efe1',
    storageBucket: 'rugodymur-9efe1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDCX4KZtHn7EP8EKZeRrK8ZkCTRNOmNs',
    appId: '1:484422805952:ios:80216f9712c8e0100dc025',
    messagingSenderId: '484422805952',
    projectId: 'rugodymur-9efe1',
    storageBucket: 'rugodymur-9efe1.firebasestorage.app',
    iosBundleId: 'com.example.rugodymur',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeaOQV19Tzky0Q_Yv_7LS4GWI7wQrfOYY',
    appId: '1:484422805952:web:efc1bbc07e6477460dc025',
    messagingSenderId: '484422805952',
    projectId: 'rugodymur-9efe1',
    authDomain: 'rugodymur-9efe1.firebaseapp.com',
    storageBucket: 'rugodymur-9efe1.firebasestorage.app',
    measurementId: 'G-C1E346DSM4',
  );
}
